# Generated by Django 4.2.5 on 2023-10-28 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashlearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packs',
            name='avg_difficulty',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='packs',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
