# Generated by Django 4.2.5 on 2023-10-29 09:11

from django.db import migrations, models
import flashlearn.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashlearn', '0002_packs_avg_difficulty_packs_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=flashlearn.models.user_image_location),
        ),
    ]
