# Generated by Django 4.2.5 on 2023-11-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashlearn', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packs',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='flashlearn.category'),
        ),
    ]
